import { $ } from "bun";
import * as path from "path";
import * as fs from "fs/promises";

type Jdk = {
  version: string;
  name: string;
  homePath: string;
  homeEnvVar: string;
  url: string;
  sha256: string;
};

const USER_HOME = process.env.HOME || process.env.USERPROFILE!;
const JDK_ROOT = path.join(USER_HOME, "jdks");

const JDK_LIST: Jdk[] = [
  {
    version: "21",
    name: "linux_aarch64",
    homePath: "jdk-21.0.2+13",
    homeEnvVar: "JAVA_HOME_LINUX_AARCH64",
    url: "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.2_13.tar.gz",
    sha256: "3ce6a2b357e2ef45fd6b53d6587aa05bfec7771e7fb982f2c964f6b771b7526a",
  },
  {
    version: "21",
    name: "linux_x64",
    homePath: "jdk-21.0.2+13",
    homeEnvVar: "JAVA_HOME_LINUX_X64",
    url: "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz",
    sha256: "454bebb2c9fe48d981341461ffb6bf1017c7b7c6e15c6b0c29b959194ba3aaa5",
  },
  {
    version: "21",
    name: "macos_aarch64",
    homePath: "jdk-21.0.2+13/Contents/Home",
    homeEnvVar: "JAVA_HOME_MACOS_AARCH64",
    url: "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_aarch64_mac_hotspot_21.0.2_13.tar.gz",
    sha256: "57d9e0f0e8639f9f2fb1837518fd83043f23953ff69a677f885aa060994d0c19",
  },
  {
    version: "21",
    name: "macos_x64",
    homePath: "jdk-21.0.2+13/Contents/Home",
    homeEnvVar: "JAVA_HOME_MACOS_X64",
    url: "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_x64_mac_hotspot_21.0.2_13.tar.gz",
    sha256: "ba696ec46c1ca2b1b64c4e9838e21a2d62a1a4b6857a0770adc64451510065db",
  },
  {
    version: "21",
    name: "windows_x64",
    homePath: "jdk-21.0.2+13",
    homeEnvVar: "JAVA_HOME_WINDOWS_X64",
    url: "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_x64_windows_hotspot_21.0.2_13.zip",
    sha256: "8780b07ae0a9836285a86a5b6d2b8a0b82acf97258622d44c619d59998a1da7b",
  },
];

async function isFileExists(filepath: string) {
  try {
    await fs.access(filepath);
    return true;
  } catch (err) {
    return false;
  }
}

async function fileSha256(filepath: string): Promise<string> {
  const file = Bun.file(filepath);
  const buffer = await file.arrayBuffer();
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(buffer);
  return hasher.digest("hex");
}

async function downloadFile(url: string, destPath: string) {
  const response = await fetch(url, { redirect: "follow" });
  if (!response.ok) {
    throw new Error(`Failed to download ${url}: ${response.status}`);
  }
  await Bun.write(destPath, response);
}

async function downloadAndExtractJdk(jdk: Jdk) {
  const filename = path.basename(jdk.url);
  const filepath = path.join(JDK_ROOT, filename);
  const jdkFullName = `JDK ${jdk.version} for '${jdk.name}'`;

  console.log(`Downloading ${jdkFullName}...`);
  let downloaded = false;
  if (await isFileExists(filepath)) {
    const sha256 = await fileSha256(filepath);
    console.log(`Sha256 of the downloaded file: '${sha256}'`);
    if (sha256 === jdk.sha256) {
      console.log(`${jdkFullName} is downloaded. SKIP`);
      downloaded = true;
    } else {
      console.log(`Removing broken ${jdkFullName}...`);
      await fs.unlink(filepath);
    }
  }
  if (!downloaded) {
    await downloadFile(jdk.url, filepath);
  }

  console.log(`Extracting ${jdkFullName}...`);
  const extractPath = path.join(JDK_ROOT, jdk.name);

  await fs.mkdir(extractPath, { recursive: true });
  if (filename.endsWith(".gz")) {
    await $`tar -xzf ${filepath} -C ${extractPath}`;
  } else if (filename.endsWith(".zip")) {
    await $`tar -xf ${filepath} -C ${extractPath}`;
  } else {
    throw new Error(`Unknown JDK archive: ${filename}`);
  }

  return [jdk.homeEnvVar, path.join(extractPath, jdk.homePath)] as const;
}

async function createEnvVars(vars: (readonly [string, string])[]) {
  // Write directly to GITHUB_ENV if in CI
  const githubEnvFile = process.env.GITHUB_ENV;
  if (githubEnvFile) {
    let content = "";
    for (const [varName, varValue] of vars) {
      content += `${varName}=${varValue}\n`;
    }
    await fs.appendFile(githubEnvFile, content);
    console.log("Exported env variables to GITHUB_ENV");
    return;
  }

  // Otherwise write shell scripts for local use
  const varExportsFilepath = path.join(USER_HOME, "java-home-vars.sh");

  let varExports = "# Generated by the JDK setup script.";
  for (const [varName, varValue] of vars) {
    varExports += `\nexport ${varName}=${varValue}`;
  }
  await fs.writeFile(varExportsFilepath, varExports);

  console.log();
  console.log(
    "Created env variables, please run the following command to take effect:"
  );
  console.log();
  console.log(`>>> source ~/${path.basename(varExportsFilepath)}`);
  console.log();
}

const start = Date.now();

console.log(`Installing ${JDK_LIST.length} JDKs...`);

console.log();
console.log("JDK ROOT:", JDK_ROOT);
console.log();

await fs.mkdir(JDK_ROOT, { recursive: true });

// Download and extract
const envVars = await Promise.all(
  JDK_LIST.map((jdk) => downloadAndExtractJdk(jdk))
);

// Create env vars
console.log();
console.log("Creating environment variables...");
await createEnvVars(envVars);

const end = Date.now();

const elapsed = ((end - start) / 1000).toFixed(2);

console.log();
console.log(
  `All ${JDK_LIST.length} JDKs are installed, took ${elapsed}s.`
);
